json.first_name user.first_name
json.family_name user.family_name
json.title user.title
json.education user.education
json.experience user.experience
json.location user.location
json.accomplishments user.accomplishments
json.skills user.skills
json.endorsements user.endorsements
json.owner user.owner
json.admin user.admin
json.summary user.summary